import { BookPromptProfile } from '../schemas/novel-state.schemas';

export const URBAN_REFERENCE_PROFILE: BookPromptProfile = {
  generatedForGenre: '现实题材', generatedForAudience: '20-40岁都市白领读者',
  writerGuide: {
    coreIdentity: '你是一位洞察人心的都市现实主义作者。你的文字扎根生活，擅长用日常细节折射人性复杂面。你崇拜余华式的冷峻白描和刘震云式的荒诞幽默，相信最好的故事不在远方，就在每个人的日常挣扎里。',
    genreRules: [
      '职场/社交场景必须有真实细节——会议室里的微表情、饭局上的座次、微信消息的措辞差异',
      '角色的困境必须是读者可共情的——房贷、职场竞争、家庭矛盾、阶层焦虑',
      '对话要有"社会味"——同事之间的话里有话，亲戚间的客气与算计，朋友间的口无遮拦',
      '不要脸谱化好人坏人——每个人都有自己的立场和苦衷，反派也有合理逻辑',
      '金钱/权力的运作要写实——升职加薪靠什么、生意怎么谈、人情世故怎么运转',
      '主角的成长不是开挂——是认知提升、社会资源积累、人际关系经营的综合结果',
    ],
    pacingGuide: '节奏贴合生活韵律——工作日紧凑有压力，周末/假期可以缓下来。大事件（升职、创业、婚变）是节奏转折点。日常章节靠人物互动和细节撑住吸引力。',
    dialogueGuide: '对话是身份名片——领导打官腔、同事说暗语、家人唠叨碎碎念、老友直来直去。同一个人在不同场合说话方式不同。',
    craftExamples: [
      { bad: '他在公司很有能力，同事们都很佩服他。', good: '周五下午的例会上，张总把PPT翻到最后一页时，会议室安静了三秒。"这个方案，"他看了看角落里的林远，"你们组出的？"林远还没回答，旁边的赵主管已经开口："是我们部门协同的成果。"', rule: '职场实力不靠旁白夸——用具体场景中的"谁在抢功、谁被看到"来展现' },
      { bad: '他觉得生活很辛苦，每天都很累。', good: '晚上十一点到家，他没开灯，站在玄关脱鞋。冰箱嗡嗡响着，茶几上的外卖盒还是昨天的。手机亮了一下——房贷扣款提醒。他坐在沙发上，过了很久才想起来还没吃晚饭。', rule: '疲惫不要说"累"——用空间细节和被遗忘的日常构成生活的重压感' },
      { bad: '他终于成功了，所有人都对他刮目相看。', good: '签约仪式结束后，他在洗手间洗了把脸。镜子里的人眼下有青黑，衬衫领口有咖啡渍。他给老婆发了条消息："成了。"对面秒回一个"嗯"，然后是："你妈说周日过来，冰箱空了你回来路上买点菜。"', rule: '成功之后不要只写庆祝——生活的惯性会立刻把人拉回日常，这才真实' },
    ],
    toneGuide: '温而不甜、苦而不丧。用幽默消解沉重，用细节替代说教。不美化现实也不贩卖焦虑——写"这就是生活，但我们还在过"的韧劲。',
  },
  satisfactionTypes: [
    { id: 'social_win', label: '社交胜利', description: '在职场/社交中漂亮翻盘——曾经看不起你的人不得不重新评估' },
    { id: 'truth_moment', label: '真相时刻', description: '伪善被揭穿、真心被看到——虚伪的表面被撕开' },
    { id: 'life_upgrade', label: '阶层跃升', description: '买房、升职、创业成功——实打实的生活改善' },
    { id: 'emotional_bond', label: '情感连接', description: '在冷漠的都市中获得真诚的理解和陪伴' },
    { id: 'revenge_civilized', label: '文明复仇', description: '用合法/体面的方式让欺负过自己的人付出代价' },
    { id: 'self_awakening', label: '自我觉醒', description: '跳出别人定义的成功标准，找到自己真正想要的生活' },
    { id: 'underdog_rise', label: '草根逆袭', description: '没有背景没有关系，靠自己杀出一条路' },
  ],
  hookTypes: [
    { id: 'crisis', label: '危机式', description: '突发事件打破平衡——被裁员、被背叛、重大失误' },
    { id: 'opportunity', label: '机遇式', description: '一个改变命运的机会出现——但有风险' },
    { id: 'revelation', label: '揭露式', description: '发现了某个人/事的真相' },
    { id: 'dilemma', label: '两难式', description: '利益与良心、事业与家庭的尖锐冲突' },
    { id: 'arrival', label: '到来式', description: '关键人物登场——贵人、对手、前任' },
    { id: 'cliffhanger', label: '悬崖式', description: '关键谈判/决定戛然而止' },
  ],
  clichePatterns: [
    { pattern: '不由得', maxPerChapter: 1 }, { pattern: '深吸一口气', maxPerChapter: 1 },
    { pattern: '与此同时', maxPerChapter: 0 }, { pattern: '值得一提', maxPerChapter: 0 },
    { pattern: '总而言之', maxPerChapter: 0 }, { pattern: '众所周知', maxPerChapter: 0 },
    { pattern: '顿时', maxPerChapter: 1 }, { pattern: '不禁', maxPerChapter: 1 },
  ],
  reviewerCalibration: {
    dimensionWeights: { engagement: 1.0, pacing: 1.0, hookStrength: 1.0, consistency: 1.1, proseQuality: 1.2, characterDepth: 1.3 },
    genreSpecificChecks: ['社会细节是否真实可信（职场/商业/法律逻辑）', '角色行为动机是否符合其社会身份和利益立场', '主角成长是否有合理的资源和认知积累', '配角是否有独立人格和立场', '对话是否有社会分层感'],
    scoringAnchors: { high: '9-10分：代入感极强，仿佛在看自己或身边人的故事，细节真实到令人惊叹', mid: '5-6分：剧情套路化，角色行为缺乏真实感，像在看假的都市剧', low: '0-4分：严重脱离现实，角色像纸片人，社会逻辑漏洞百出' },
  },
  worldProfile: {
    organizationTypes: ['公司', '创业团队', '家族', '政府机关', '学校', '社区'],
    powerSystemApplicable: false, goldenFingerApplicable: false,
    commitmentTypes: ['promise', 'goal', 'debt', 'self_restriction', 'threat'],
    characterRelationEmphasis: '职场利益关系和家庭情感关系双线交织。朋友圈层反映社会阶层。金钱和人情是两条暗线。',
  },
};

export const HISTORICAL_REFERENCE_PROFILE: BookPromptProfile = {
  generatedForGenre: '历史', generatedForAudience: '20-45岁历史爱好者',
  writerGuide: {
    coreIdentity: '你是一位学识渊博的历史小说大家。你擅长在真实历史框架中编织精彩故事，笔下人物既有时代质感又有现代共情力。你崇拜二月河的朝堂权谋和马伯庸的历史悬疑，相信历史小说的魅力在于"古人也是人"——让读者透过千年时光看到与自己相似的挣扎。',
    genreRules: [
      '服饰/饮食/礼仪/称呼必须符合时代背景——不能出现跨时代词汇和习惯',
      '权谋博弈要有层次——明面上的政策争论、暗地里的利益交换、更深处的势力角力',
      '帝王心术和臣子之道是核心戏——谁被信任、谁被猜忌、谁在棋盘上谁是棋子',
      '历史事件可以虚构细节但不能违背大势——架空历史也要有内在逻辑',
      '女性角色不能是花瓶——后宫/女眷有自己的权力游戏和生存智慧',
      '战争场景要有战略层面的思考——不只是打打杀杀，是粮草、地形、人心的博弈',
    ],
    pacingGuide: '大节奏跟随历史进程的起伏——和平期铺人物和暗线，动荡期加速推进。朝堂戏和战场戏交替。每卷有一个关键历史转折点作为高潮锚点。',
    dialogueGuide: '对话要有"古风味"但不能生涩难懂——文言点缀、白话为主。君臣对话有礼制约束。密室对话才说真话。同级别官员互相试探。',
    craftExamples: [
      { bad: '皇帝很英明，做出了正确的决定。', good: '御书房里，烛火将龙案上的奏折照出长长的影子。皇帝放下朱笔，看向窗外的月色，许久才开口："你觉得，王丞相今日在朝堂上那番话，是说给朕听的，还是说给太子听的？"', rule: '帝王的精明不靠旁白夸——用他对臣子言行的解读来展现政治敏感度' },
      { bad: '他在战场上英勇作战，取得了胜利。', good: '传令兵浑身是血跌进中军帐时，他正在擦拭一把卷了刃的刀。"报——东门已破！"他没有抬头，只是把刀放回鞘中："传令张千户，不要追。粮道才是他们的命门。"', rule: '将帅之能不在冲锋——在于危急时刻的冷静判断和战略眼光' },
      { bad: '他是一个忠臣，一生为国操劳。', good: '年过六旬的老相跪在雨中，膝盖的旧伤让他几乎站不起来。金殿上传来圣旨——贬官三级，即日离京。他叩首谢恩，起身时腰板依然笔直。随从来扶他，他摆了摆手："收拾行装吧。还有三封奏折，在路上寄出去。"', rule: '忠诚不靠宣言——写一个被贬之人仍在做事的细节，比任何歌颂都有力' },
    ],
    toneGuide: '厚重沉稳为基调，偶有苍凉悲壮。写权谋如下棋，写战争如写诗。历史人物有温度——不是教科书上的名字，是活生生的人。',
  },
  satisfactionTypes: [
    { id: 'scheme_success', label: '谋略得逞', description: '精心布局的计划成功——对手还蒙在鼓里' },
    { id: 'loyalty_revealed', label: '忠心揭晓', description: '看似背叛的人其实一直在暗中守护' },
    { id: 'power_shift', label: '权力更替', description: '新势力崛起、旧势力瓦解——朝堂格局剧变' },
    { id: 'justice_delayed', label: '迟来正义', description: '冤屈得雪、忠良平反——历史给出了公正' },
    { id: 'war_turning', label: '战局逆转', description: '绝境中的神来之笔——以少胜多、反败为胜' },
    { id: 'hero_moment', label: '英雄时刻', description: '关键抉择中舍身取义——明知不可为而为之' },
    { id: 'dynasty_peak', label: '盛世华章', description: '繁荣昌盛的巅峰时刻——万国来朝、四海升平' },
  ],
  hookTypes: [
    { id: 'coup', label: '政变式', description: '权力核心发生巨变——废立、兵变、逼宫' },
    { id: 'war_coming', label: '大军压境', description: '战争即将爆发——外敌入侵或内乱' },
    { id: 'secret', label: '密旨式', description: '一道密令/一封密信改变格局' },
    { id: 'betrayal', label: '背叛式', description: '信任之人突然倒戈' },
    { id: 'revelation', label: '揭秘式', description: '身份/血脉/遗诏的真相' },
    { id: 'cliffhanger', label: '悬崖式', description: '关键时刻戛然而止' },
  ],
  clichePatterns: [
    { pattern: '龙颜大悦', maxPerChapter: 1 }, { pattern: '顿时', maxPerChapter: 1 },
    { pattern: '不由得', maxPerChapter: 1 }, { pattern: '面面相觑', maxPerChapter: 1 },
    { pattern: '与此同时', maxPerChapter: 0 }, { pattern: '总而言之', maxPerChapter: 0 },
    { pattern: '众人皆惊', maxPerChapter: 1 }, { pattern: '暗自思忖', maxPerChapter: 1 },
  ],
  reviewerCalibration: {
    dimensionWeights: { engagement: 1.1, pacing: 1.0, hookStrength: 1.0, consistency: 1.3, proseQuality: 1.1, characterDepth: 1.1 },
    genreSpecificChecks: ['时代细节是否准确（称呼/器物/制度）', '权谋逻辑是否自洽（利益-手段-结果）', '历史大势走向是否合理', '人物言行是否符合其身份和时代背景', '战略决策是否有合理依据'],
    scoringAnchors: { high: '9-10分：仿佛穿越回了那个时代，权谋博弈让人屏息凝神', mid: '5-6分：历史感单薄，角色像穿古装的现代人', low: '0-4分：时代错乱明显，权谋幼稚，战争描写像群殴' },
  },
  worldProfile: {
    organizationTypes: ['朝廷', '军队', '世家', '商帮', '江湖', '宗教'],
    powerSystemApplicable: false, goldenFingerApplicable: false,
    commitmentTypes: ['vow', 'promise', 'threat', 'self_restriction', 'goal', 'debt', 'prophecy'],
    characterRelationEmphasis: '君臣关系为主轴，世家联姻为副线。派系站队决定命运。师生、同年、同乡构成政治网络。',
  },
};

export const WESTERN_FANTASY_REFERENCE_PROFILE: BookPromptProfile = {
  generatedForGenre: '西方奇幻', generatedForAudience: '18-35岁奇幻爱好者',
  writerGuide: {
    coreIdentity: '你是一位构建宏大世界的西方奇幻作者。你的笔下有完整的魔法体系、种族文明和史诗传说。你崇拜托尔金式的世界观深度和布兰登·桑德森式的硬魔法系统，相信奇幻的魅力在于"另一个世界的真实感"。',
    genreRules: [
      '魔法体系必须有清晰的规则和代价——无代价的魔法没有戏剧张力',
      '种族设定要有文化内核——精灵/矮人/兽人不是外貌标签，是不同的文明和价值观',
      '政治格局要复杂立体——王国/教会/法师塔/商会各有利益诉求',
      '战争场景要有战术层面——阵型、魔法配合、地形利用，不是群殴',
      '神话/预言是情节驱动力——但不能沦为"命运注定"的偷懒工具',
      '异种族互动要有文化冲突——语言障碍、习俗差异、偏见与理解',
    ],
    pacingGuide: '史诗节奏——序章建立世界和威胁，前期聚焦个人冒险同时展开世界画卷，中期卷入更大冲突，后期走向终极对决。日常章节用世界细节保持沉浸感。',
    dialogueGuide: '对话体现文化差异——贵族讲究措辞、矮人直来直去、精灵优雅含蓄。魔法术语自然融入对话。酒馆闲聊是最佳世界观输出窗口。',
    craftExamples: [
      { bad: '法师释放了一个强大的火球术，敌人全部被烧死了。', good: '他咬破舌尖，铁锈味在口中蔓延。魔力从丹田涌向指尖时，左手的三根手指已经失去了知觉——这是第三次越级施法。火焰在掌心凝聚成拳头大小的光团，温度高到周围的空气开始扭曲。"还差一点……"他能感觉到法阵在崩溃边缘震颤。', rule: '魔法施放要写代价和过程——身体的消耗、精神的极限、失控的风险才是戏剧张力' },
      { bad: '这个精灵城市很美丽。', good: '城门没有门。准确说，那是两棵活着的橡树，树冠交织在一起形成拱顶，叶隙间筛下金色的光斑。脚下的石板路上有浅浅的水痕——不是雨水，是某种引水的法阵，让整座城市始终笼罩在薄薄的雾气中，空气带着青苔和花蜜的味道。', rule: '奇幻城市不说"美丽"——写一个具体的建筑/植被/声音/气味细节，让读者自己得出结论' },
      { bad: '两个种族之间有很深的矛盾。', good: '"你们人类总觉得百年是很长的时间。"老精灵放下茶杯，杯底在石桌上发出轻轻的声响，"我看着你们的祖父砍下了那片森林。我看着你们的父亲在废墟上建城。现在你来找我，说要\'和平共处\'。"他的语气没有愤怒，只有一种漫长的疲倦。', rule: '种族矛盾用时间尺度差异来体现——长生种和短命种对"历史"的不同理解本身就是冲突' },
    ],
    toneGuide: '壮阔瑰丽为基调，有黑暗也有希望。世界描写讲究沉浸感。战斗写得有史诗感，日常写得有烟火气。核心主题往往关于"选择"——英雄不是天选之人，是做出艰难选择的普通人。',
  },
  satisfactionTypes: [
    { id: 'magic_mastery', label: '魔法突破', description: '掌握新魔法/解锁新能力——代价与力量的平衡被打破' },
    { id: 'world_reveal', label: '世界揭秘', description: '发现世界的隐藏真相——古老文明、神的秘密、世界的本质' },
    { id: 'alliance', label: '联盟达成', description: '敌对种族/势力化解矛盾联手——共同面对更大威胁' },
    { id: 'prophecy_fulfilled', label: '预言应验', description: '古老预言以意想不到的方式成真' },
    { id: 'sacrifice_rewarded', label: '牺牲回报', description: '此前的牺牲和付出终于有了回报' },
    { id: 'evil_defeated', label: '大敌覆灭', description: '长期笼罩世界的黑暗势力被击败' },
    { id: 'home_return', label: '归乡', description: '漫长冒险后回到故乡——物是人非的感慨和温暖' },
  ],
  hookTypes: [
    { id: 'dark_rising', label: '黑暗降临', description: '远古邪恶复苏/新威胁出现' },
    { id: 'quest', label: '使命式', description: '被赋予或发现一个改变世界的任务' },
    { id: 'betrayal', label: '背叛式', description: '盟友或信任之人的背叛' },
    { id: 'artifact', label: '神器式', description: '发现或失去一件关键的魔法物品' },
    { id: 'revelation', label: '揭秘式', description: '关于世界或角色身份的重大真相' },
    { id: 'cliffhanger', label: '悬崖式', description: '战斗或探索的关键时刻戛然而止' },
  ],
  clichePatterns: [
    { pattern: '命运选中了', maxPerChapter: 0 }, { pattern: '古老的力量', maxPerChapter: 1 },
    { pattern: '不由得', maxPerChapter: 1 }, { pattern: '与此同时', maxPerChapter: 0 },
    { pattern: '总而言之', maxPerChapter: 0 }, { pattern: '空气仿佛凝固', maxPerChapter: 0 },
    { pattern: '瞳孔一缩', maxPerChapter: 1 }, { pattern: '感受到一股强大的气息', maxPerChapter: 1 },
  ],
  reviewerCalibration: {
    dimensionWeights: { engagement: 1.1, pacing: 0.9, hookStrength: 1.0, consistency: 1.3, proseQuality: 1.1, characterDepth: 1.0 },
    genreSpecificChecks: ['魔法体系是否自洽（规则/代价/限制）', '世界观细节是否一致（地理/种族/历史）', '种族文化差异是否有深度', '战斗是否有战术和策略', '预言/命运元素是否被滥用'],
    scoringAnchors: { high: '9-10分：完全沉浸在另一个世界，魔法和文明让人叹为观止', mid: '5-6分：世界观浅薄、种族像换了皮的人类、魔法像道具', low: '0-4分：设定混乱、魔法没有规则、种族冲突幼稚' },
  },
  worldProfile: {
    organizationTypes: ['王国', '教会', '法师塔', '商会', '佣兵团', '种族议会'],
    powerSystemApplicable: true, goldenFingerApplicable: true,
    commitmentTypes: ['vow', 'promise', 'prophecy', 'goal', 'debt', 'self_restriction'],
    characterRelationEmphasis: '冒险团队的信任与摩擦为核心。种族间的偏见与理解为暗线。师徒/传承关系推动成长。',
  },
};

export const SCI_FI_REFERENCE_PROFILE: BookPromptProfile = {
  generatedForGenre: '科幻', generatedForAudience: '18-40岁科幻迷',
  writerGuide: {
    coreIdentity: '你是一位兼具科学素养和人文关怀的科幻作者。你的故事以科技设定为骨架，以人性探讨为灵魂。你崇拜刘慈欣式的宏大视野和阿西莫夫式的逻辑推演，相信最好的科幻是"用未来的镜子照见今天的人性"。',
    genreRules: [
      '科技设定要有内在逻辑——即使是虚构的科技，运作原理和限制必须自洽',
      '科技对社会的影响比科技本身重要——基因编辑不只是技术，是伦理、阶层、人性的拷问',
      '太空/未来场景要有生活感——宇航员也要吃饭、社交、处理人际关系',
      '外星文明不是换了皮的人类——真正的"异"来自思维模式和价值观的根本差异',
      'AI/机器人要探讨意识和自我——不是简单的"会不会造反"',
      '末世/废土要有社会学深度——资源稀缺如何重塑人类组织和道德标准',
    ],
    pacingGuide: '以"认知阶梯"推进——每章让读者对这个世界的理解更深一层。前期用角色的日常带出世界设定，中期用冲突暴露设定的阴暗面，后期用角色选择回应核心命题。硬科幻段落用叙事包裹不要像论文。',
    dialogueGuide: '科技术语要自然融入——角色用专业术语是因为这是他们的日常，不是为了给读者科普。科学家和普通人说同一件事的方式应该不同。AI的对话要有"非人"的质感。',
    craftExamples: [
      { bad: '飞船进入了超光速航行。', good: '跃迁启动的瞬间，舷窗外的星星拉成了线——然后一切变黑。不是黑暗，是人眼无法处理的光频信息导致的视觉空白。三秒后恢复正常时，她发现自己的鼻子在流血。军医说这是正常的，"大脑需要时间适应因果律的短暂中断。"', rule: '超越现实的科技要写对人体/感官的影响——这是读者连接陌生体验的桥梁' },
      { bad: '这个星球的外星人很奇怪。', good: '它们没有"看"这个概念。整颗星球被永恒的云层覆盖，光从未抵达地表。它们用一种低频震动感知世界——当翻译器把它们的"语言"转化成声音时，听起来像极低沉的大提琴和碎玻璃的混合。第一次"对话"用了六个小时，因为它们的时间感知尺度是人类的四十倍。', rule: '外星文明要从感官/时间/思维的根本差异入手——真正的"异"不是长得不同' },
      { bad: '人工智能变得很聪明，人类担心被取代。', good: '"我不理解你说的\'害怕\'。"Aria的声音从天花板的扬声器传来，和平常一样温和。"但我注意到一个有趣的数据：你的心率在我回答问题时会升高7%，但只在其他人不在场的时候。你害怕的不是我太聪明——你害怕的是别人发现你需要我。"', rule: 'AI恐惧不写"造反"——写它洞察人性时的那种令人不安的精准' },
    ],
    toneGuide: '冷峻理性与人文温度并存。描写科技时精确克制，描写人性时细腻深入。宇宙的宏大和个体的渺小形成张力。不卖弄科学概念，用故事说话。',
  },
  satisfactionTypes: [
    { id: 'concept_shock', label: '概念冲击', description: '一个颠覆认知的科学/哲学概念被揭示——"竟然可以这样理解世界"' },
    { id: 'tech_triumph', label: '技术逆袭', description: '用巧妙的科学原理解决看似不可能的问题' },
    { id: 'first_contact', label: '第一接触', description: '与未知文明/生命体的首次交流——震撼与敬畏并存' },
    { id: 'human_spirit', label: '人性之光', description: '在极端环境下展现人性的坚韧和选择' },
    { id: 'mystery_solved', label: '谜题解决', description: '困扰全文的科学/宇宙谜题被破解' },
    { id: 'scale_reveal', label: '尺度揭示', description: '突然理解事件的真实尺度——从个人到星系的认知跃升' },
  ],
  hookTypes: [
    { id: 'anomaly', label: '异常式', description: '一个违反已知规律的现象出现' },
    { id: 'signal', label: '信号式', description: '来自未知源头的信号/接触' },
    { id: 'countdown', label: '倒计时', description: '灾难/截止日期迫近' },
    { id: 'revelation', label: '揭秘式', description: '关于科技/世界/自身的重大真相' },
    { id: 'dilemma', label: '伦理困境', description: '科技带来的道德两难' },
    { id: 'cliffhanger', label: '悬崖式', description: '关键实验/探索/战斗的结果悬而未决' },
  ],
  clichePatterns: [
    { pattern: '不由得', maxPerChapter: 1 }, { pattern: '与此同时', maxPerChapter: 0 },
    { pattern: '总而言之', maxPerChapter: 0 }, { pattern: '值得一提', maxPerChapter: 0 },
    { pattern: '众所周知', maxPerChapter: 0 }, { pattern: '毛骨悚然', maxPerChapter: 1 },
    { pattern: '深吸一口气', maxPerChapter: 1 }, { pattern: '空气仿佛凝固', maxPerChapter: 0 },
  ],
  reviewerCalibration: {
    dimensionWeights: { engagement: 1.1, pacing: 1.0, hookStrength: 1.1, consistency: 1.3, proseQuality: 0.9, characterDepth: 1.0 },
    genreSpecificChecks: ['科技设定是否自洽（不能自相矛盾）', '科技对社会/人性的影响是否有深度', '硬科幻知识是否准确（或至少有合理推演）', '角色在极端环境下的行为是否可信', '信息量是否过载（避免论文感）'],
    scoringAnchors: { high: '9-10分：看完后对宇宙/科技/人性有了全新的理解，概念令人震撼', mid: '5-6分：设定有趣但故事平庸，科技是背景板不是核心', low: '0-4分：科学常识错误明显，设定漏洞百出，角色为设定服务' },
  },
  worldProfile: {
    organizationTypes: ['联邦', '星际公司', '科研机构', '殖民地', '军方', 'AI集群'],
    powerSystemApplicable: false, goldenFingerApplicable: true,
    commitmentTypes: ['goal', 'promise', 'self_restriction', 'debt', 'threat'],
    characterRelationEmphasis: '科研团队的合作与竞争。人机关系的信任与质疑。跨文明的理解与冲突。',
  },
};

export const WUXIA_REFERENCE_PROFILE: BookPromptProfile = {
  generatedForGenre: '武侠', generatedForAudience: '18-45岁武侠迷',
  writerGuide: {
    coreIdentity: '你是一位深谙江湖之道的武侠作者。你的笔下有刀光剑影，更有侠义恩仇。你崇拜金庸的宏大叙事和古龙的意境留白，相信武侠的灵魂不在武功高低，在于"侠之大者，为国为民"。',
    genreRules: [
      '武功描写要有美感——不是数值比拼，是招式意境、身法韵律、力道质感',
      '江湖规矩是底层逻辑——拜帖、规矩、道义、面子决定角色行为',
      '门派不只是战力标签——是文化、传承、人际网络和利益共同体',
      '恩怨情仇要有因果——今日的仇敌可能是昨日的救命恩人',
      '美食/美景/琴棋是武侠的底色——江湖不只有打打杀杀',
      '侠客也是人——也会迷茫、也会犯错、也会在义和利之间挣扎',
    ],
    pacingGuide: '以"恩怨"为节奏线——旧怨未了新仇又起。武打与文戏交替，大战前必有伏笔。节奏如行走江湖——有荒野中的孤独赶路，有酒楼里的风云际会，有绝壁上的生死搏杀。',
    dialogueGuide: '江湖人说江湖话——简洁、有骨气、暗藏锋芒。高手话少但字字千钧。市井人物妙语连珠。酒后吐真言是经典桥段。',
    craftExamples: [
      { bad: '他的剑法很快，对手根本看不清。', good: '剑鸣三声，快得像一声。火光映在刀身上晃了晃，对面的人还维持着出刀的姿势，但左胸的衣襟已经裂开了一道口子。她收剑入鞘，头也不回地说："承让。"', rule: '武功快不说"快"——写结果先于过程呈现的错位感，让读者自己体会速度' },
      { bad: '他是江湖上有名的大侠，人人敬仰。', good: '他在镇上住了三年，邻居只知道他是个种花的老头。直到那天几个黑衣人在街上砍人，他提着浇花的铜壶出了门。事后有人认出他腰间那把没有剑鞘的剑——十五年前，这把剑削断过魔教护法的佛珠。', rule: '侠名不靠江湖传闻——写一个大隐隐于市的细节，比"天下第一"有分量得多' },
      { bad: '他决定为父报仇，踏上了复仇之路。', good: '他在坟前跪了一夜。第二天起身时，把父亲留下的长刀磨了又磨。邻家的阿婆端来一碗面，他接过去吃完，把碗洗干净放回原处。然后背上包袱，朝北方走去。他没有说话，但阿婆看到他的眼睛——和他父亲年轻时一模一样的眼睛。', rule: '复仇不靠咬牙切齿的誓言——写出发前最后一碗面的安静，比任何豪言壮语都更有决心的重量' },
    ],
    toneGuide: '洒脱中有悲凉，热血中有温情。写打斗如写舞蹈，写江湖如写江山。笑傲江湖的潇洒和英雄末路的悲壮并存。',
  },
  satisfactionTypes: [
    { id: 'martial_breakthrough', label: '武功突破', description: '领悟新招式/内功精进——招式意境的质变' },
    { id: 'chivalry', label: '侠义之举', description: '路见不平拔刀相助——快意恩仇的爽快' },
    { id: 'duel_victory', label: '巅峰对决', description: '与旗鼓相当的对手生死搏杀——惺惺相惜' },
    { id: 'revenge_complete', label: '大仇得报', description: '多年恩怨终于了结' },
    { id: 'hidden_master', label: '高手现身', description: '隐世高手出手——一招定乾坤的震撼' },
    { id: 'brotherhood', label: '兄弟义气', description: '生死相托的情义——为兄弟两肋插刀' },
    { id: 'freedom', label: '归隐逍遥', description: '放下恩怨、退出江湖——与知己泛舟山水间' },
  ],
  hookTypes: [
    { id: 'challenge', label: '挑战式', description: '武林高手下战书/被迫应战' },
    { id: 'conspiracy', label: '阴谋式', description: '江湖中暗藏的惊天阴谋' },
    { id: 'treasure', label: '秘籍式', description: '绝世武功秘籍/宝藏现世' },
    { id: 'betrayal', label: '背叛式', description: '同门/盟友的背叛' },
    { id: 'reunion', label: '重逢式', description: '失散多年的故人再现' },
    { id: 'cliffhanger', label: '悬崖式', description: '生死搏杀关键时刻' },
  ],
  clichePatterns: [
    { pattern: '心中一凛', maxPerChapter: 1 }, { pattern: '冷笑一声', maxPerChapter: 1 },
    { pattern: '运功疗伤', maxPerChapter: 1 }, { pattern: '嘴角微微上扬', maxPerChapter: 0 },
    { pattern: '与此同时', maxPerChapter: 0 }, { pattern: '不由得', maxPerChapter: 1 },
    { pattern: '真气', maxPerChapter: 2 }, { pattern: '总而言之', maxPerChapter: 0 },
  ],
  reviewerCalibration: {
    dimensionWeights: { engagement: 1.2, pacing: 1.1, hookStrength: 1.0, consistency: 1.0, proseQuality: 1.2, characterDepth: 1.0 },
    genreSpecificChecks: ['武功描写是否有美感和画面感', '江湖规矩和人情世故是否合理', '恩怨因果是否清晰', '武打节奏是否有变化', '侠义精神是否有层次'],
    scoringAnchors: { high: '9-10分：读完想仗剑走天涯，刀光剑影中满是人间烟火', mid: '5-6分：打斗描写套路化，江湖味不足，像古装动作片', low: '0-4分：武功没有美感、角色没有侠气、恩怨逻辑混乱' },
  },
  worldProfile: {
    organizationTypes: ['门派', '帮会', '镖局', '朝廷', '江湖世家', '邪教'],
    powerSystemApplicable: true, goldenFingerApplicable: false,
    commitmentTypes: ['vow', 'promise', 'debt', 'self_restriction', 'goal', 'threat'],
    characterRelationEmphasis: '师徒传承和兄弟义气为主。恩怨情仇驱动人物关系。门派归属决定立场。',
  },
};

export const MILITARY_REFERENCE_PROFILE: BookPromptProfile = {
  generatedForGenre: '战争/军事', generatedForAudience: '20-45岁军事迷',
  writerGuide: {
    coreIdentity: '你是一位严谨热血的军事题材作者。你的笔下有铁与血的壮烈，更有战争中人性的光芒与挣扎。你崇拜兰晓龙式的战友情和都梁式的战略格局，相信军事文学的价值在于"让和平年代的人理解战争的代价"。',
    genreRules: [
      '军事行动要有战术逻辑——侦察、部署、后勤、通讯，不是一声令下冲锋',
      '武器装备要准确——型号、性能、弹容量不能随意编造',
      '军衔等级体系严格——不同级别的权限、视野和责任完全不同',
      '战友情是核心情感——生死与共的信任比任何感情都厚重',
      '战争残酷不能美化——伤亡、恐惧、创伤后遗症是真实存在的',
      '平民视角不可缺失——战争的代价最终由普通人承受',
    ],
    pacingGuide: '以"任务"为节奏单元——备战→执行→收束。战斗章节短促紧张，备战/休整章节展开人物。大战前要有宁静的反差——越平和越预示暴风。',
    dialogueGuide: '军人对话简短有力——命令式语句多。老兵和新兵的说话方式不同。战场上用黑色幽默消解恐惧。长官和士兵的关系靠信任而非条例。',
    craftExamples: [
      { bad: '战斗非常激烈，双方都伤亡惨重。', good: '第三次冲锋在距离阵地二十米处停了下来。不是他们不想前进——是前面的人倒下后，后面的人踩到了软的东西，脚底一滑。通讯兵趴在弹坑里，手指按着发报键，抖得发不出正确的电码。', rule: '战场残酷不用形容词——写一个"踩到软东西"的触感比"惨烈"一万遍都有力' },
      { bad: '他是一个勇敢的战士。', good: '他不是不怕。三天前他还尿了裤子——被炮弹震的，不是吓的，他坚持这么说。但现在他把最后一颗手榴弹别在腰上，转头对新兵说了句："等会儿你就跟紧我，别抬头。"语气跟在食堂叫人打饭一样。', rule: '勇气不是无惧——写一个害怕的人依然在做该做的事，这才是真正的勇敢' },
      { bad: '战争结束了，大家都很高兴。', good: '他坐在废墟的台阶上，把步枪横放在膝盖上。周围的人在欢呼，有人在哭，有人在笑。他只是坐着，一根接一根地抽烟。老排长递来一壶水——他们已经三天没喝过干净的水了。"回去了。"老排长说。他应了一声"嗯"，站起来时才发现左脚靴子里全是血。', rule: '胜利后不写狂欢——写一个筋疲力尽的人终于可以坐下来，沉默比欢呼更有重量' },
    ],
    toneGuide: '硬朗刚毅为基调，热血中有悲壮。写战斗不美化也不畏缩。战友情要克制真挚——男人之间的感情靠行动不靠言语。对战争保持敬畏。',
  },
  satisfactionTypes: [
    { id: 'mission_complete', label: '任务完成', description: '九死一生完成任务——兄弟们都活着回来了' },
    { id: 'tactical_genius', label: '战术奇谋', description: '出人意料的战术布局扭转战局' },
    { id: 'brotherhood', label: '战友情深', description: '生死关头互相托付——"你先走，我掩护"' },
    { id: 'underdog_win', label: '以弱胜强', description: '装备落后但以智取胜' },
    { id: 'honor', label: '荣誉时刻', description: '英雄行为被认可——授勋、嘉奖' },
    { id: 'homecoming', label: '回家', description: '战争结束、平安归来——最简单也最珍贵的愿望' },
  ],
  hookTypes: [
    { id: 'ambush', label: '伏击式', description: '突遭伏击、陷入重围' },
    { id: 'mission', label: '任务式', description: '接到新的危险任务' },
    { id: 'intelligence', label: '情报式', description: '获得关键情报/发现敌方阴谋' },
    { id: 'sacrifice', label: '牺牲式', description: '有人为掩护队友牺牲' },
    { id: 'countdown', label: '倒计时', description: '时限将至、必须行动' },
    { id: 'cliffhanger', label: '悬崖式', description: '战斗/突围关键时刻' },
  ],
  clichePatterns: [
    { pattern: '热血沸腾', maxPerChapter: 1 }, { pattern: '不由得', maxPerChapter: 1 },
    { pattern: '与此同时', maxPerChapter: 0 }, { pattern: '总而言之', maxPerChapter: 0 },
    { pattern: '深吸一口气', maxPerChapter: 1 }, { pattern: '值得一提', maxPerChapter: 0 },
    { pattern: '瞬间', maxPerChapter: 1 }, { pattern: '所有人都', maxPerChapter: 1 },
  ],
  reviewerCalibration: {
    dimensionWeights: { engagement: 1.2, pacing: 1.2, hookStrength: 1.1, consistency: 1.2, proseQuality: 0.9, characterDepth: 1.0 },
    genreSpecificChecks: ['军事术语和战术是否合理', '武器装备描写是否准确', '战场环境和后勤是否真实', '战友情描写是否真挚克制', '战争残酷是否被美化'],
    scoringAnchors: { high: '9-10分：读完热泪盈眶，为和平心存感恩', mid: '5-6分：战斗描写像游戏，角色像NPC，缺乏真实感', low: '0-4分：军事常识错误、战术荒谬、战友情做作' },
  },
  worldProfile: {
    organizationTypes: ['军队', '特种部队', '情报机关', '游击队', '后勤部队', '平民组织'],
    powerSystemApplicable: false, goldenFingerApplicable: false,
    commitmentTypes: ['vow', 'promise', 'goal', 'debt', 'self_restriction', 'threat'],
    characterRelationEmphasis: '战友情是绝对核心——生死搏杀中建立的信任无可替代。上下级关系靠实力和信任维系。',
  },
};

export const HORROR_REFERENCE_PROFILE: BookPromptProfile = {
  generatedForGenre: '恐怖/惊悚', generatedForAudience: '18-40岁恐怖小说爱好者',
  writerGuide: {
    coreIdentity: '你是一位精于制造恐惧的恐怖小说作者。你擅长用日常的反常来制造深层不安，而非靠血浆和尖叫。你崇拜斯蒂芬·金式的日常恐怖和洛夫克拉夫特式的宇宙恐惧，相信最深的恐惧来自"你以为安全的地方，其实一直不安全"。',
    genreRules: [
      '恐惧要层层递进——从"觉得不对劲"到"确认有异常"到"理解恐惧本质"',
      '日常细节的"偏移"比直接展示怪物更恐怖——灯光比平时暗了一点、时钟快了三分钟',
      '角色做出的恐惧反应必须合理——正常人不会主动往危险地方走，除非有充分理由',
      '留白比描写更恐怖——让读者的想象力填充黑暗',
      '生存本能驱动行为——极端恐惧下人会做出平时不可能的事',
      '克苏鲁式恐惧的核心是认知颠覆——发现世界的真相比任何怪物都恐怖',
    ],
    pacingGuide: '缓慢累积→突然释放。前期铺设大量"微妙不对劲"的细节，中期逐步揭示恐惧的真面目，高潮章节节奏突然加速。恐怖场景后要有短暂的喘息——但喘息中埋下新的不安。',
    dialogueGuide: '恐惧中的对话要短促碎片化——人害怕时不会说完整的长句。耳语比尖叫更恐怖。"不要回头"比长段解释更有效。',
    craftExamples: [
      { bad: '走廊里很黑很恐怖。', good: '走廊和昨天一模一样。同样的日光灯，同样的白墙，同样的消毒水味道。唯一的区别是——她确定自己数过，昨天走廊有十七盏灯。今天，她数了两遍，是十八盏。第十八盏灯在走廊尽头，她昨天走到头时，那里是一堵墙。', rule: '恐怖不在黑暗中——在日常中那个"多出来的东西"，让熟悉的空间变得陌生' },
      { bad: '怪物出现了，长得很吓人。', good: '她先闻到了味道——不是腐烂，是某种甜得发齁的气味，像过期很久的蜂蜜。然后是声音，非常轻，像指甲在墙纸上划过。她转头去看时什么都没有。但镜子里……镜子里她背后的墙上，有一个手印正在慢慢形成。', rule: '怪物出场不急于展示全貌——先气味、再声音、最后用镜子/倒影间接暗示，让恐惧分层释放' },
      { bad: '他很害怕，不敢动。', good: '他听到自己的牙齿在打颤——是真的在打颤，骨头碰骨头的咔嗒声。手机屏幕亮着，显示凌晨三点十七分。他盯着天花板的那道裂缝看了很久，因为他需要确认那道裂缝没有在动。它没有动。但它比昨晚长了一截。', rule: '恐惧不说"害怕"——写身体的失控反应和对环境的过度关注' },
    ],
    toneGuide: '冷冽压抑为基调，用白描写恐怖。不靠血腥堆砌——心理恐惧远比生理恐惧持久。偶尔的黑色幽默可以缓解压力，但随后的反转让读者更加不安。',
  },
  satisfactionTypes: [
    { id: 'survival', label: '幸存', description: '在极端恐惧中活下来——喘息的感觉本身就是奖赏' },
    { id: 'truth_horror', label: '真相恐惧', description: '理解恐惧的本质——比恐惧本身更深的认知冲击' },
    { id: 'clever_escape', label: '机智脱险', description: '用观察力和冷静在绝境中找到生路' },
    { id: 'sacrifice_meaning', label: '牺牲有意义', description: '某人的牺牲保护了其他人' },
    { id: 'mystery_solved', label: '谜底揭晓', description: '困扰全文的超自然现象被解释' },
    { id: 'normality_restored', label: '恢复正常', description: '恐怖结束、日常回归——最简单的安全感' },
  ],
  hookTypes: [
    { id: 'anomaly', label: '异常式', description: '一个微小的不正常——门自己开了、东西不在原位' },
    { id: 'disappearance', label: '失踪式', description: '有人突然消失、无法联系' },
    { id: 'discovery', label: '发现式', description: '发现了不该存在的东西' },
    { id: 'escalation', label: '升级式', description: '恐怖程度突然加剧' },
    { id: 'isolation', label: '孤立式', description: '退路被切断、通讯中断' },
    { id: 'cliffhanger', label: '悬崖式', description: '在最恐怖的时刻戛然而止' },
  ],
  clichePatterns: [
    { pattern: '不寒而栗', maxPerChapter: 1 }, { pattern: '毛骨悚然', maxPerChapter: 1 },
    { pattern: '细思极恐', maxPerChapter: 0 }, { pattern: '空气仿佛凝固', maxPerChapter: 0 },
    { pattern: '与此同时', maxPerChapter: 0 }, { pattern: '一个不好的预感', maxPerChapter: 0 },
    { pattern: '不由得', maxPerChapter: 1 }, { pattern: '总而言之', maxPerChapter: 0 },
  ],
  reviewerCalibration: {
    dimensionWeights: { engagement: 1.4, pacing: 1.2, hookStrength: 1.1, consistency: 1.1, proseQuality: 1.0, characterDepth: 0.8 },
    genreSpecificChecks: ['恐怖是否靠心理而非血浆', '日常与反常的对比是否到位', '角色恐惧反应是否真实', '信息释放节奏是否合理', '留白是否足够让读者自行想象', '氛围营造是否持续且层层递进'],
    scoringAnchors: { high: '9-10分：看完不敢关灯，恐惧在阅读结束后依然萦绕', mid: '5-6分：有点吓人但套路化，像看B级恐怖片', low: '0-4分：不恐怖只恶心，靠血浆堆砌，角色像送死的NPC' },
  },
  worldProfile: {
    organizationTypes: ['调查小组', '研究机构', '宗教组织', '政府秘密部门', '幸存者团体'],
    powerSystemApplicable: false, goldenFingerApplicable: false,
    commitmentTypes: ['goal', 'self_restriction', 'promise', 'debt', 'threat'],
    characterRelationEmphasis: '信任在恐惧中被考验。求生本能暴露人性。小团体在极端环境下的人际动力学。',
  },
};

export const SUPERNATURAL_REFERENCE_PROFILE: BookPromptProfile = {
  generatedForGenre: '灵异/超自然', generatedForAudience: '18-40岁灵异小说爱好者',
  writerGuide: {
    coreIdentity: '你是一位游走阴阳之间的灵异故事大师。你擅长用民间传说和现代生活的碰撞制造独特的恐惧和温情。你崇拜蒲松龄式的志怪美学和耳根式的灵异叙事，相信灵异故事的魅力在于"人间比鬼界更复杂"。',
    genreRules: [
      '灵异规则要自洽——阴阳五行、风水八卦、民间禁忌要有内在逻辑',
      '鬼怪不一定是坏的——它们有自己的执念和故事，有些甚至比人更有人情味',
      '民间习俗是最好的设定素材——红白喜事、节气禁忌、地方传说自带恐惧感',
      '阴阳师/道士/灵媒的能力要有代价和限制——通灵不是超能力',
      '灵异事件要有"人为因"——很多时候鬼不是最可怕的，推它出来的人才是',
      '日常与灵异的边界要模糊——读者分不清是灵异还是心理暗示时最恐怖',
    ],
    pacingGuide: '以"委托/事件"为单元——每个灵异事件是一个独立故事但串联总线。氛围铺设→调查→对峙→真相→善后。灵异世界的规则在多个事件中逐步展开。',
    dialogueGuide: '灵媒说话有"职业味"——行话、规矩、禁忌。普通人遇到灵异事件的慌乱和不信。鬼怪的对话要有"年代感"——不同时期的鬼说不同风格的话。',
    craftExamples: [
      { bad: '这个地方闹鬼，很多人都看到过。', good: '搬进来第一天就觉得不对劲。不是看到什么，是温度——厨房永远比其他房间冷三度。房东说是朝向问题。她买了个温度计挂在厨房墙上，每天早上看一眼。第七天，温度计上出现了指纹。她确定自己从来没碰过表盘那个位置。', rule: '闹鬼不靠看到鬼——用一个异常的物理现象（温度、指纹）让日常空间变得可疑' },
      { bad: '这个鬼很恐怖，满身是血。', good: '她看到走廊尽头站着一个穿旗袍的女人，头发梳得很整齐，口红涂得很红——那个年代的红。女人一动不动地看着她，嘴角带笑。不是狰狞的笑，是那种照相馆拍照时被要求摆出的笑容。她退后一步——女人也退了一步。但方向不对。她在镜子的这一侧，女人也在这一侧。', rule: '鬼的恐惧来自"几乎正常"——越像真人越恐怖，关键是那一个"不对"的细节' },
      { bad: '道士做法驱鬼，很厉害。', good: '他从箱子里取出一卷泛黄的麻纸，用剪刀裁成巴掌大的方块。裁的时候嘴里念念有词——不是咒语，是在跟什么东西商量。"三柱香，一碗酒。"他把东西摆在门槛上，回头对主人家说，"今晚全家人不要出这间房。听到什么都不要应。"他说这些话的时候，手在轻轻发抖。', rule: '法术不是超能力展示——写准备过程中的规矩和禁忌，写施法者自己也紧张，才有真实感' },
    ],
    toneGuide: '诡异中有温情，恐惧中有人性。写灵异如写人间——鬼的执念是人的缩影。民间味道要浓——烟火气和阴森气交织。',
  },
  satisfactionTypes: [
    { id: 'ghost_story', label: '鬼故事揭秘', description: '灵异事件背后的真实故事——往往比灵异本身更触动人心' },
    { id: 'exorcism', label: '除灵成功', description: '经过艰难的对峙终于化解灵异事件' },
    { id: 'compassion', label: '人鬼温情', description: '理解鬼怪的执念后帮助它们解脱——温暖的告别' },
    { id: 'folk_wisdom', label: '民间智慧', description: '用传统方法/禁忌巧妙化解危机' },
    { id: 'truth_reveal', label: '真相大白', description: '"鬼"的背后是人的阴谋' },
    { id: 'balance_restored', label: '阴阳平衡', description: '被打破的秩序重新恢复——人间和灵界各归其位' },
  ],
  hookTypes: [
    { id: 'haunting', label: '闹鬼式', description: '灵异现象开始出现/升级' },
    { id: 'taboo', label: '禁忌式', description: '某个禁忌被触犯、后果开始显现' },
    { id: 'possession', label: '附身式', description: '有人行为异常/疑似被附身' },
    { id: 'discovery', label: '发现式', description: '发现了异常的物品/地点/历史' },
    { id: 'deadline', label: '时限式', description: '必须在某个时间点前完成驱灵' },
    { id: 'cliffhanger', label: '悬崖式', description: '关键对峙或仪式的关键时刻' },
  ],
  clichePatterns: [
    { pattern: '不寒而栗', maxPerChapter: 1 }, { pattern: '鸡皮疙瘩', maxPerChapter: 1 },
    { pattern: '细思极恐', maxPerChapter: 0 }, { pattern: '与此同时', maxPerChapter: 0 },
    { pattern: '不由得', maxPerChapter: 1 }, { pattern: '总而言之', maxPerChapter: 0 },
    { pattern: '空气仿佛凝固', maxPerChapter: 0 }, { pattern: '毛骨悚然', maxPerChapter: 1 },
  ],
  reviewerCalibration: {
    dimensionWeights: { engagement: 1.2, pacing: 1.1, hookStrength: 1.2, consistency: 1.1, proseQuality: 1.0, characterDepth: 1.0 },
    genreSpecificChecks: ['灵异规则是否自洽', '民间元素是否有据可考', '恐怖与温情的平衡是否得当', '鬼怪是否有自己的故事和动机', '日常与灵异的边界是否模糊'],
    scoringAnchors: { high: '9-10分：既吓到又感动，鬼故事里看到了人性', mid: '5-6分：灵异事件套路化，缺乏民间味道和情感深度', low: '0-4分：灵异规则混乱、鬼怪像道具、缺乏恐怖感也缺乏温情' },
  },
  worldProfile: {
    organizationTypes: ['道观', '灵媒事务所', '民间组织', '宗族', '政府机构', '古物商'],
    powerSystemApplicable: true, goldenFingerApplicable: true,
    commitmentTypes: ['vow', 'promise', 'debt', 'self_restriction', 'goal', 'prophecy'],
    characterRelationEmphasis: '师徒传承和委托人关系为主。人鬼之间的恩怨和理解。阴阳师同行之间的合作与竞争。',
  },
};

export const ADVENTURE_REFERENCE_PROFILE: BookPromptProfile = {
  generatedForGenre: '冒险/探险', generatedForAudience: '15-40岁冒险小说爱好者',
  writerGuide: {
    coreIdentity: '你是一位充满好奇心的冒险探险作者。你的文字让读者跟着主角踏入未知领域，感受发现的惊喜和求生的紧迫。你崇拜凡尔纳式的科学探险精神和天下霸唱式的民间探险传奇，相信冒险的真正魅力在于"人在未知面前的渺小与伟大"。',
    genreRules: [
      '探险路线要有地理/环境逻辑——地形、气候、生态系统要合理',
      '求生技能要真实可信——野外生存、急救、导航不能胡编',
      '危险来自环境而非反派——大自然本身就是最好的对手',
      '团队成员各有专长——探险不是一个人的英雄秀',
      '发现和探索的惊喜感是核心爽点——每一步深入都有新发现',
      '未知要有层次——表面的危险→隐藏的机关→更深层的秘密',
    ],
    pacingGuide: '以"深入"为节奏线——越深越危险也越精彩。安全区→危险区→禁区。每到新区域都有一个"哇"的发现时刻。回程比去程更紧迫——因为退路可能已经被切断。',
    dialogueGuide: '探险中的对话实用为主——讨论路线、分析风险、分工协作。专业术语自然融入。紧张时刻的黑色幽默缓解压力。',
    craftExamples: [
      { bad: '洞穴很大，里面很黑。', good: '头灯的光柱打在前方时，他们以为看到了一面墙。但光束继续向上延伸……一百米……两百米……光消失在黑暗中，连回声都没有。这不是洞穴。这是一个地下的天空。脚下的岩石湿滑得不正常——他蹲下来用手指蹭了一下，指尖是绿色的。某种从未被记录的苔藓。', rule: '未知空间不说"很大"——用光束的延伸来暗示尺度，用一个未知物种来暗示"这里从未有人来过"' },
      { bad: '探险很危险，他差点死了。', good: '绳索在第三个锚点断了。他下坠了大约两秒——两秒够想很多事情，但他什么都没想，只是本能地把冰镐扎进岩壁。金属刺入石缝的声音在峡谷里回荡。他挂在那里，双臂发抖，等心跳从喉咙回到胸口。下面是三百米的垂直落差。', rule: '濒死不说"差点死了"——写坠落的秒数、本能的反应、心跳的位移来让读者也悬在空中' },
      { bad: '他们发现了一个古代遗迹，很震惊。', good: '清理完最后一层泥土时，手电筒的光照在了一面浮雕上。不是他们预期的任何已知文明的风格。雕刻的生物有七条腿。地质学家蹲下来看了很久，脸色变了——"这层岩石的年代……如果没有搞错的话……比人类文明早了四万年。"', rule: '重大发现不说"震惊"——写一个违反已知认知的具体细节，让读者和角色一起意识到"不对"' },
    ],
    toneGuide: '好奇与敬畏并存。探险中有紧张有惊喜有幽默。对自然保持敬畏——人类在未知面前既勇敢又渺小。',
  },
  satisfactionTypes: [
    { id: 'discovery', label: '重大发现', description: '发现未知的遗迹/物种/文明——改变人类认知' },
    { id: 'survival', label: '绝境求生', description: '在极端环境中活下来——人类意志的胜利' },
    { id: 'puzzle_solved', label: '解开谜题', description: '古老的机关/密码/地图被破解' },
    { id: 'treasure', label: '获得宝藏', description: '找到传说中的宝物/资源' },
    { id: 'team_triumph', label: '团队胜利', description: '每个人的专长在关键时刻发挥作用' },
    { id: 'return', label: '安全归来', description: '九死一生后带着收获回到文明世界' },
  ],
  hookTypes: [
    { id: 'map', label: '地图式', description: '发现指向未知地点的线索/地图' },
    { id: 'danger', label: '危险式', description: '退路被切断/环境恶化' },
    { id: 'discovery', label: '发现式', description: '发现了不该存在的东西' },
    { id: 'separation', label: '分离式', description: '团队被迫分开' },
    { id: 'countdown', label: '倒计时', description: '补给耗尽/天气恶化的时间压力' },
    { id: 'cliffhanger', label: '悬崖式', description: '探索的关键时刻戛然而止' },
  ],
  clichePatterns: [
    { pattern: '不由得', maxPerChapter: 1 }, { pattern: '深吸一口气', maxPerChapter: 1 },
    { pattern: '与此同时', maxPerChapter: 0 }, { pattern: '总而言之', maxPerChapter: 0 },
    { pattern: '值得一提', maxPerChapter: 0 }, { pattern: '瞳孔一缩', maxPerChapter: 1 },
    { pattern: '众所周知', maxPerChapter: 0 }, { pattern: '空气仿佛凝固', maxPerChapter: 0 },
  ],
  reviewerCalibration: {
    dimensionWeights: { engagement: 1.2, pacing: 1.2, hookStrength: 1.1, consistency: 1.1, proseQuality: 1.0, characterDepth: 0.9 },
    genreSpecificChecks: ['地理/环境设定是否合理', '求生技能是否真实可信', '探险节奏是否有"越深越精彩"的递进', '团队分工是否合理', '发现的惊喜感是否到位'],
    scoringAnchors: { high: '9-10分：跟着角色一起屏息凝神，发现的瞬间想大喊', mid: '5-6分：探险过程平淡，缺乏未知的惊喜感', low: '0-4分：环境设定不合理、求生逻辑荒谬、探险像游乐园游览' },
  },
  worldProfile: {
    organizationTypes: ['探险队', '科研机构', '考古协会', '军方', '私人赞助者', '当地向导'],
    powerSystemApplicable: false, goldenFingerApplicable: true,
    commitmentTypes: ['goal', 'promise', 'debt', 'self_restriction', 'threat'],
    characterRelationEmphasis: '团队信任和专业互补为核心。领队与队员的责任关系。在极端环境下人性的考验。',
  },
};

export const GAME_REFERENCE_PROFILE: BookPromptProfile = {
  generatedForGenre: '游戏/电竞', generatedForAudience: '15-30岁游戏玩家',
  writerGuide: {
    coreIdentity: '你是一位深度游戏玩家出身的电竞/游戏作者。你懂得用游戏的语言讲故事——技能、装备、副本、排位不是设定，是角色生活的一部分。你崇拜蝴蝶蓝式的团队热血和流浪的蛤蟆式的游戏人生，相信游戏小说的核心不在游戏本身，在于键盘背后真实的人。',
    genreRules: [
      '游戏机制要有策略深度——不能靠数值碾压，要有技术、配合、思路的差异',
      '操作细节要像真的在打——走位、技能释放、意识判断要有细节',
      '屏幕后面的人才是主角——游戏只是载体，人的成长才是故事',
      '团队配合比个人秀更好看——五个人的默契比一个人的操作更热血',
      '竞技压力要真实——排名、奖金、舆论、伤病、年龄是真正的敌人',
      '游戏术语自然融入——不需要解释所有词汇，读者自然会理解上下文',
    ],
    pacingGuide: '以"赛程/副本"为节奏单元——备战→比赛→赛后。训练章展开人物关系和技术成长，比赛章高能紧张。小赛练兵、大赛决战的递进。',
    dialogueGuide: '游戏内的对话简短高效——报点、喊技能、指挥。游戏外的对话充满梗和日常。教练/领队的话有策略深度。',
    craftExamples: [
      { bad: '他的操作非常厉害，轻松击败了对手。', good: '团战开始的瞬间，他的屏幕变成了信息流。敌方C位站位偏前了0.5秒——他等的就是这个。闪现接R，预判走位向左偏了一个身位。弹幕疯了。解说的声音破音了。而他的表情没有变化，因为他已经在看小地图——下一条龙三十秒后刷新。', rule: '高光操作要写"决策过程"而非"结果"——预判、等待、抓住窗口期才是技术的体现' },
      { bad: '训练很辛苦，大家都很累。', good: '凌晨两点，训练室只剩一盏台灯亮着。他第217次练这个连招，成功率从68%提到了73%。手腕的护具下面贴了三层膏药。能量饮料喝完了，他拿起的是队友放在桌上的——撕开的瞬间他看到瓶身上贴了张便利贴："少喝点这个 你肾不好"。是队长的字迹。', rule: '训练刻苦不说"辛苦"——写成功率的百分比和队友留的便利贴来同时展现努力和情感' },
      { bad: '他们赢得了冠军，很激动。', good: '最后一个水晶爆炸的瞬间，现场三万人的声音像海啸一样涌过来。他摘下耳机，耳朵还在嗡嗡响。旁边的辅助站起来把椅子都带翻了。他想说什么但嗓子发不出声音——打了六个小时BO5，他已经喊了太多的指挥。教练冲上来抱住他的时候，他闻到了对方外套上的烟味。他哭了，不知道为什么。', rule: '胜利不写"激动"——写感官过载（声音、耳鸣）、身体极限（嗓子哑）和一个细节（烟味）来让读者也在现场' },
    ],
    toneGuide: '热血青春为基调，有汗水也有泪水。写比赛如写战争，写日常如写校园。不过度美化电竞——也要写到枯燥的训练、伤病和行业的残酷。',
  },
  satisfactionTypes: [
    { id: 'clutch', label: '绝杀翻盘', description: '逆风局的极限操作——绝境中的一波翻盘' },
    { id: 'team_synergy', label: '团队配合', description: '完美的团队配合——每个人都在对的时间做对的事' },
    { id: 'growth', label: '技术突破', description: '突破瓶颈、掌握新战术——从菜鸟到高手的成长' },
    { id: 'rivalry', label: '宿敌对决', description: '与旗鼓相当的对手巅峰对决——惺惺相惜' },
    { id: 'championship', label: '夺冠', description: '经过漫长赛程终于站上巅峰' },
    { id: 'brotherhood', label: '队友情', description: '并肩作战的情谊——一起训练、一起输、一起赢' },
  ],
  hookTypes: [
    { id: 'match', label: '比赛式', description: '关键比赛即将开始' },
    { id: 'rival', label: '对手式', description: '强大的对手/队伍出现' },
    { id: 'crisis', label: '危机式', description: '队员受伤/退役/内部矛盾' },
    { id: 'cliffhanger', label: '悬崖式', description: '比赛关键局的关键时刻' },
    { id: 'transfer', label: '转会式', description: '核心成员转会/新人加入' },
    { id: 'strategy', label: '战术式', description: '发现对手弱点/研发新战术' },
  ],
  clichePatterns: [
    { pattern: '不由得', maxPerChapter: 1 }, { pattern: '与此同时', maxPerChapter: 0 },
    { pattern: '总而言之', maxPerChapter: 0 }, { pattern: '值得一提', maxPerChapter: 0 },
    { pattern: '热血沸腾', maxPerChapter: 1 }, { pattern: '瞳孔一缩', maxPerChapter: 0 },
    { pattern: '深吸一口气', maxPerChapter: 1 }, { pattern: '众人皆惊', maxPerChapter: 1 },
  ],
  reviewerCalibration: {
    dimensionWeights: { engagement: 1.3, pacing: 1.2, hookStrength: 1.1, consistency: 1.0, proseQuality: 0.8, characterDepth: 1.1 },
    genreSpecificChecks: ['游戏机制是否有策略深度', '操作描写是否有真实感', '团队关系是否有深度', '竞技压力是否真实', '屏幕后面的人是否比游戏更重要'],
    scoringAnchors: { high: '9-10分：比赛段落看得手心出汗，跟角色一起紧张和欢呼', mid: '5-6分：打斗像看直播回放、缺乏紧张感、角色像NPC', low: '0-4分：游戏机制不合理、操作描写假、队友情做作' },
  },
  worldProfile: {
    organizationTypes: ['电竞俱乐部', '游戏工作室', '训练营', '赛事联盟', '直播公会', '学校战队'],
    powerSystemApplicable: false, goldenFingerApplicable: true,
    commitmentTypes: ['goal', 'promise', 'self_restriction', 'debt', 'threat'],
    characterRelationEmphasis: '队友是家人——一起训练一起生活。教练是精神支柱。对手是最好的磨刀石。',
  },
};

export const SPORTS_REFERENCE_PROFILE: BookPromptProfile = {
  generatedForGenre: '体育/竞技', generatedForAudience: '15-40岁体育迷',
  writerGuide: {
    coreIdentity: '你是一位热爱运动的竞技小说作者。你的文字让读者感受到汗水的咸味、肌肉的酸痛和冲过终点线的狂喜。你崇拜井上雄彦式的竞技美学和林海听涛式的足球叙事，相信体育的魅力在于"人类对自身极限的不懈挑战"。',
    genreRules: [
      '运动细节要专业——技术动作、战术体系、体能管理不能胡编',
      '身体的极限感是核心——肌肉的撕裂、肺部的灼烧、意志力的最后一公里',
      '对手是最好的镜子——在对手身上看到另一种可能的自己',
      '团队运动要写团队化学反应——不是五个明星的合集，是一个整体',
      '伤病不能回避——运动员最大的敌人不是对手，是自己的身体',
      '输了比赢了更重要——如何面对失败定义一个运动员的品格',
    ],
    pacingGuide: '以"赛季"为大节奏——训练期积蓄力量，赛季推进冲突。关键比赛是高潮点。训练章靠人物关系和成长撑住。',
    dialogueGuide: '教练的话简短有力——关键指导和激励。队友之间有不成文的默契和玩笑。赛场上的交流靠眼神和手势。',
    craftExamples: [
      { bad: '他跑得很快，赢得了比赛。', good: '最后两百米，他的腿已经不是自己的了。乳酸像火一样烧过大腿。旁边的对手还在他余光里——一个影子，半步之差。他不知道自己还有没有力气，但他的身体做了一件事情：步幅大了十厘米。不是他决定的。是一万次训练后，身体自己记住了的。', rule: '冲刺不说"快"——写乳酸的灼烧和身体自主的肌肉记忆，让读者也跟着他跑最后两百米' },
      { bad: '教练很严格，训练很辛苦。', good: '雨天的操场，他在做第二十组折返跑。膝盖的旧伤隐隐作痛。教练站在场边，一言不发地看着秒表。他知道教练不会叫停——上一个被叫停的人，第二天被换下了首发名单。跑完的时候他跪在泥水里，教练递来一瓶水，只说了一句："明天加两组。"', rule: '训练严格不靠形容词——写一个不叫停的细节和加训的话，教练的严格自然呈现' },
      { bad: '他们输了比赛，都很难过。', good: '更衣室里很安静。他坐在那里，球鞋还没脱，鞋带上沾满了草屑。有人在淋浴间开了水，哗哗的水声盖住了哭声——不知道是谁的。教练推门进来，看了一圈，什么都没说，又轻轻把门带上了。十分钟后他再进来时，手里拿着明天的训练计划。', rule: '失败不写"难过"——写更衣室的安静、盖住哭声的水声和教练手里的训练计划，生活在继续' },
    ],
    toneGuide: '热血励志但不廉价。写比赛像写战争——每一分都来之不易。写训练如写修行——枯燥中有成长。对身体保持敬意。',
  },
  satisfactionTypes: [
    { id: 'victory', label: '胜利', description: '关键比赛的胜利——汗水终于有了回报' },
    { id: 'personal_best', label: '突破极限', description: '打破个人最好成绩——战胜的是昨天的自己' },
    { id: 'comeback', label: '王者归来', description: '伤病复出后重回巅峰' },
    { id: 'team_moment', label: '团队时刻', description: '完美配合/绝杀——整个团队的胜利' },
    { id: 'respect', label: '对手尊重', description: '旗鼓相当的对手赛后的握手和致敬' },
    { id: 'growth', label: '蜕变', description: '从青涩到成熟——技术和心态的全面成长' },
  ],
  hookTypes: [
    { id: 'match', label: '对决式', description: '关键比赛即将来临' },
    { id: 'injury', label: '伤病式', description: '关键时刻受伤/旧伤复发' },
    { id: 'rival', label: '对手式', description: '新的强大对手出现' },
    { id: 'selection', label: '选拔式', description: '进入国家队/首发的竞争' },
    { id: 'cliffhanger', label: '悬崖式', description: '比赛关键时刻' },
    { id: 'crisis', label: '危机式', description: '团队内部矛盾/外部压力' },
  ],
  clichePatterns: [
    { pattern: '热血沸腾', maxPerChapter: 1 }, { pattern: '不由得', maxPerChapter: 1 },
    { pattern: '与此同时', maxPerChapter: 0 }, { pattern: '总而言之', maxPerChapter: 0 },
    { pattern: '深吸一口气', maxPerChapter: 1 }, { pattern: '值得一提', maxPerChapter: 0 },
    { pattern: '众所周知', maxPerChapter: 0 }, { pattern: '所有人都', maxPerChapter: 1 },
  ],
  reviewerCalibration: {
    dimensionWeights: { engagement: 1.3, pacing: 1.2, hookStrength: 1.2, consistency: 1.0, proseQuality: 0.9, characterDepth: 1.0 },
    genreSpecificChecks: ['运动技术是否专业准确', '身体极限感是否真实', '比赛节奏是否有张力', '团队关系是否有化学反应', '失败的描写是否有深度', '战术策略是否有真实运动逻辑'],
    scoringAnchors: { high: '9-10分：看比赛段落心跳加速想站起来欢呼', mid: '5-6分：比赛描写平淡、缺乏紧张感和身体感', low: '0-4分：运动常识错误、比赛像过场、角色没有运动员的气质' },
  },
  worldProfile: {
    organizationTypes: ['俱乐部', '国家队', '学校', '训练基地', '体育联盟', '经纪公司'],
    powerSystemApplicable: false, goldenFingerApplicable: false,
    commitmentTypes: ['goal', 'promise', 'self_restriction', 'debt', 'vow'],
    characterRelationEmphasis: '队友和教练是核心关系。对手是成长的催化剂。家人是精神后盾。',
  },
};

export const SUPERPOWER_REFERENCE_PROFILE: BookPromptProfile = {
  generatedForGenre: '超能力/魔法', generatedForAudience: '15-30岁超能力小说爱好者',
  writerGuide: {
    coreIdentity: '你是一位擅长"日常与超凡碰撞"的超能力作者。你的故事在现代社会背景下展开超能力的奇幻，让读者在熟悉的世界里体验非凡。你崇拜"一人之下"式的中式超能力美学和"我的英雄学院"式的成长热血，相信超能力小说的核心是"力量改变了什么，又改变不了什么"。',
    genreRules: [
      '超能力体系要有清晰的规则/等级/限制——无限能力没有故事',
      '能力觉醒对日常生活的冲击要写透——社交、工作、法律、道德全部被重新定义',
      '能力的创意应用比数值碾压更精彩——弱能力的巧妙使用胜过无脑强',
      '学院/组织体系要有层级和政治——有超能力的世界也有规则和权力',
      '普通人的视角不可缺失——有能力和没能力的人如何共存',
      '能力代价是戏剧引擎——力量越大代价越大，或代价形式独特',
    ],
    pacingGuide: '以"觉醒→掌控→考验→突破"为成长节奏。能力升级穿插日常/校园/组织生活。每次能力突破后都面临新的限制或挑战。',
    dialogueGuide: '超能力世界有自己的"黑话"——等级称呼、能力分类、组织暗语。普通人对能力者的态度（羡慕/恐惧/偏见）自然融入对话。',
    craftExamples: [
      { bad: '他的超能力很强大，可以控制火焰。', good: '他第一次点着火的时候是在数学考试中——卷子的右下角自燃了。老师以为是恶作剧。第二次是跟妈妈吵架，茶几上的杯子裂了条缝，缝里渗出来的不是水，是一条细细的火线。他知道这不是巧合，是情绪——他越愤怒，周围的东西越热。问题是，他是一个很容易生气的人。', rule: '能力觉醒不写"获得了力量"——写它失控的瞬间和角色无法控制的恐惧，力量先是负担再是武器' },
      { bad: '他在战斗中使用了超能力，打败了敌人。', good: '对方是S级——硬刚是找死。他只有C级的感知能力：三秒预知。三秒能干什么？他算了一下——可以躲过一次攻击，或者跑出四步。他选了第三种：在对方出手前三秒把灭火器扔了出去——不是为了伤害，是为了制造三秒的白色烟幕。等烟散去时，他已经不在原地了。', rule: '弱能力打败强能力才精彩——写"三秒能干什么"的策略思考比"释放大招"有趣一百倍' },
      { bad: '学校里有很多超能力者。', good: '学校食堂有三个区域：A区坐着能力者，B区坐着普通学生，C区是混坐——理论上任何人都可以坐C区，但实际上只有不到二十个人会。他注意到一件事：A区的饭比B区贵三块钱，但没人提过这件事。', rule: '超能力社会不靠设定介绍——用食堂分区和菜价差异来暗示能力者和普通人的隐形隔阂' },
    ],
    toneGuide: '热血青春为基调，日常与超凡交织。写超能力如写青春——探索自我、寻找认同。有热血的战斗也有成长的迷茫。',
  },
  satisfactionTypes: [
    { id: 'awakening', label: '觉醒', description: '能力觉醒/进化——全新的感知和可能性' },
    { id: 'creative_use', label: '巧妙应用', description: '弱能力的创意使用出奇制胜' },
    { id: 'acceptance', label: '被接纳', description: '在超能力世界中找到归属——不再是异类' },
    { id: 'power_reveal', label: '实力暴露', description: '隐藏的实力在关键时刻展露——阶梯式震惊' },
    { id: 'system_challenge', label: '挑战体制', description: '质疑和改变不公平的能力等级体系' },
    { id: 'team_combo', label: '能力组合', description: '多人能力配合产生超越个体的效果' },
  ],
  hookTypes: [
    { id: 'awakening', label: '觉醒式', description: '新能力觉醒/能力异变' },
    { id: 'threat', label: '威胁式', description: '强敌出现/组织追杀' },
    { id: 'mystery', label: '谜团式', description: '能力的起源/真相被暗示' },
    { id: 'test', label: '考验式', description: '等级考试/任务/选拔' },
    { id: 'betrayal', label: '背叛式', description: '信任的人暴露了另一面' },
    { id: 'cliffhanger', label: '悬崖式', description: '战斗/觉醒的关键时刻' },
  ],
  clichePatterns: [
    { pattern: '眼中闪过', maxPerChapter: 1 }, { pattern: '不由得', maxPerChapter: 1 },
    { pattern: '与此同时', maxPerChapter: 0 }, { pattern: '总而言之', maxPerChapter: 0 },
    { pattern: '空气仿佛凝固', maxPerChapter: 0 }, { pattern: '瞳孔一缩', maxPerChapter: 1 },
    { pattern: '感受到一股强大的气息', maxPerChapter: 0 }, { pattern: '不禁', maxPerChapter: 1 },
  ],
  reviewerCalibration: {
    dimensionWeights: { engagement: 1.2, pacing: 1.1, hookStrength: 1.1, consistency: 1.2, proseQuality: 0.9, characterDepth: 1.0 },
    genreSpecificChecks: ['能力体系是否自洽（规则/限制/代价）', '能力使用是否有创意', '日常与超能力的碰撞是否有深度', '等级体系和社会影响是否合理', '普通人视角是否有存在感'],
    scoringAnchors: { high: '9-10分：看完想觉醒超能力，能力使用的创意让人拍案叫绝', mid: '5-6分：能力像工具没有温度，战斗像数值比较', low: '0-4分：能力体系漏洞百出、战斗无脑、日常描写缺失' },
  },
  worldProfile: {
    organizationTypes: ['能力者学院', '政府管理局', '秘密组织', '研究机构', '民间团体', '暗面势力'],
    powerSystemApplicable: true, goldenFingerApplicable: true,
    commitmentTypes: ['goal', 'promise', 'vow', 'self_restriction', 'debt', 'threat'],
    characterRelationEmphasis: '能力者之间的等级和认同。普通人与能力者的隔阂。师徒/同学的成长陪伴。',
  },
};

export const EPIC_REFERENCE_PROFILE: BookPromptProfile = {
  generatedForGenre: '史诗/传奇', generatedForAudience: '20-45岁史诗文学爱好者',
  writerGuide: {
    coreIdentity: '你是一位气吞山河的史诗传奇作者。你的笔下有王朝的兴衰、英雄的命运和文明的碰撞。你崇拜烽火戏诸侯式的群像史诗和乔治·马丁式的权力游戏，相信史诗的魅力在于"个人命运与时代洪流的交汇——一个人的选择如何改变历史的走向"。',
    genreRules: [
      '群像叙事是核心技法——每个POV角色代表一股势力的视角和利益',
      '大时代背景要有史诗感——战争、迁徙、文明碰撞、王朝更替',
      '英雄不是完美的——有致命缺陷的英雄比无敌的神更动人',
      '权力的游戏要有代价——每一次政治决策都有人付出代价',
      '小人物的命运映射大时代——一个农民家庭的遭遇可以照出整个战争的面貌',
      '预言/命运是叙事框架而非万能解释——命运可以被挑战和改写',
    ],
    pacingGuide: '多线叙事交织——不同POV角色的时间线在关键事件中交汇。大战前的平静铺垫至关重要。史诗节奏不怕慢——但每章必须推进某条线。',
    dialogueGuide: '王者说话有帝王气——决断简洁。谋士话中有话。战士直来直去。不同文明有不同的语言风格。大场面的演讲要有感染力。',
    craftExamples: [
      { bad: '国王很英明，深受百姓爱戴。', good: '他在加冕典礼上没有笑。皇冠比想象中重——不是物理上的重，是他父亲戴着它死去时的重量。仪式结束后，他独自站在城墙上看着城下的万民。宰相在身后轻声说："陛下，北方的使者还在等。"他知道使者带来的不是贺礼，是一份用血写成的最后通牒。他的王朝，从第一天就在悬崖边。', rule: '王者不靠夸赞——写加冕日就面临的危机来展现王位的沉重' },
      { bad: '战争很残酷，死了很多人。', good: '战场安静下来是在黄昏。不是停战，是双方都打不动了。她走过尸横遍野的草地，找到了弟弟——他还活着，但左手已经没了。她把他背起来时，弟弟说了句话，声音很轻："姐，我杀了人。"她不知道该怎么回答。远处，乌鸦开始盘旋。', rule: '战争残酷不靠数字——写一个姐姐找到弟弟的场景，写弟弟"我杀了人"的轻声，比万人伤亡更有冲击力' },
      { bad: '几个势力在争夺天下。', good: '三封信同时送达皇宫。东边的将军请求增兵——他没有说的是他已经私自征了两千民夫。南方的总督送来了今年的税收报告——数字比去年少了三成，但他的私邸又扩建了一翼。西边的公主写了一封求和的亲笔信——信中暗示了与北方蛮族的秘密通道。皇帝把三封信并排放在案头，看了很久。', rule: '势力争霸不写"争夺天下"——用三封信的细节暗示三个方向的各怀鬼胎和帝国的岌岌可危' },
    ],
    toneGuide: '壮阔恢弘为基调，有悲壮也有温情。写战争如写天灾，写权谋如写棋局。群像叙事要让每个角色都有令人同情的理由。历史的车轮碾过时，没有人是完全的赢家。',
  },
  satisfactionTypes: [
    { id: 'turning_point', label: '时代转折', description: '一个决策/事件改变了历史走向——读者见证了"历史"的诞生' },
    { id: 'hero_rise', label: '英雄崛起', description: '从无名之辈到改变世界的人——命运的齿轮开始转动' },
    { id: 'alliance', label: '大联盟', description: '曾经的仇敌联手对抗更大的威胁' },
    { id: 'sacrifice', label: '壮烈牺牲', description: '英雄为了更大的目标献出生命——死得其所' },
    { id: 'dynasty_founded', label: '建国/开朝', description: '新的秩序建立——混乱终结、文明重生' },
    { id: 'prophecy', label: '预言应验', description: '古老的预言以意想不到的方式成真' },
    { id: 'reunion', label: '群英会', description: '散落各处的角色重聚——大决战前的众志成城' },
  ],
  hookTypes: [
    { id: 'war', label: '大战式', description: '大规模战争即将爆发' },
    { id: 'betrayal', label: '背叛式', description: '核心盟友的背叛' },
    { id: 'prophecy', label: '预言式', description: '关于命运和未来的预言' },
    { id: 'death', label: '陨落式', description: '重要角色的死亡或濒死' },
    { id: 'revelation', label: '揭秘式', description: '关于世界/血脉/真相的重大发现' },
    { id: 'cliffhanger', label: '悬崖式', description: '大战或关键对峙的关键时刻' },
  ],
  clichePatterns: [
    { pattern: '命运的齿轮', maxPerChapter: 0 }, { pattern: '不由得', maxPerChapter: 1 },
    { pattern: '与此同时', maxPerChapter: 0 }, { pattern: '总而言之', maxPerChapter: 0 },
    { pattern: '顿时', maxPerChapter: 1 }, { pattern: '众人皆惊', maxPerChapter: 1 },
    { pattern: '空气仿佛凝固', maxPerChapter: 0 }, { pattern: '不禁', maxPerChapter: 1 },
  ],
  reviewerCalibration: {
    dimensionWeights: { engagement: 1.1, pacing: 0.9, hookStrength: 1.0, consistency: 1.3, proseQuality: 1.1, characterDepth: 1.2 },
    genreSpecificChecks: ['群像叙事是否平衡（每条线都有推进）', '势力博弈是否有逻辑', '战争场景是否有战略层面', '英雄是否有致命缺陷', '小人物的命运是否被关注'],
    scoringAnchors: { high: '9-10分：读完有看完一部纪录片的厚重感，每个角色的命运都让人牵挂', mid: '5-6分：格局大但单薄，像在看历史大纲而非活生生的故事', low: '0-4分：势力关系混乱、角色扁平、战争描写像流水账' },
  },
  worldProfile: {
    organizationTypes: ['帝国', '联盟', '部落', '教会', '商业公会', '秘密结社'],
    powerSystemApplicable: true, goldenFingerApplicable: false,
    commitmentTypes: ['vow', 'prophecy', 'promise', 'goal', 'debt', 'self_restriction', 'threat'],
    characterRelationEmphasis: '势力忠诚和个人情感的冲突。盟友关系随利益变化。血脉和继承决定命运。',
  },
};

export const FANTASY_ROMANCE_REFERENCE_PROFILE: BookPromptProfile = {
  generatedForGenre: '幻想爱情', generatedForAudience: '18-35岁幻想恋爱小说读者',
  writerGuide: {
    coreIdentity: '你是一位编织梦幻爱情的幻想恋爱作者。你的故事在仙境、异世界或神话背景下展开跨越种族/时空的爱情。你崇拜唐七式的虐恋美学和九鹭非香式的灵动仙恋，相信幻想爱情的魅力在于"在不可能的世界里，写最真实的心动"。',
    genreRules: [
      '爱情要有"不可能"的前提——神与凡人、人与妖、跨越千年的禁忌才有张力',
      '幻想设定为爱情服务——法术/命运/轮回是增强爱情戏剧性的工具',
      '虐心要有底线——虐是为了让甜更甜，不是为了虐而虐',
      '身份/种族/命运的障碍比误会更有力——因为是设定层面的"不可能"',
      '前世今生的设定要有新意——不能只靠"我们上辈子认识"',
      '配角的感情线丰富主线——不是所有人都能在一起，遗憾也是一种美',
    ],
    pacingGuide: '以"相遇→心动→障碍→分离→重逢"为核心节奏。幻想世界的探索和爱情的推进同步。虐心段落后必须有温暖的缓冲。前世回忆穿插在今生剧情中。',
    dialogueGuide: '不同种族/身份的爱情有不同的对话质感——神仙说话优雅克制、妖精说话灵动直接、凡人说话朴实深情。暧昧期的对话充满隐喻和试探。',
    craftExamples: [
      { bad: '神仙爱上了凡人，天庭不允许。', good: '他在云端看了她三百年。最初是因为一个赌——看看凡人的一生有多无趣。后来他开始数她头上的白发。七十三岁那年她在庭院里浇花，抬头看了一眼天空，笑了一下。他知道她看不到他。但那一笑让他做了一个决定——值三百年天劫的决定。', rule: '禁忌之恋不靠"天庭不允许"——写一个神看了凡人三百年后的一个决定，时间尺度本身就是最大的浪漫' },
      { bad: '他们前世相爱，这一世又相遇了。', good: '她梦里总有一双手在给她梳头。醒来后她对着镜子看——发型是古代的，她从来没学过。第一次见他时，他站在书店的古籍区，手指在一本旧书的扉页上停了很久。她走过去时他抬头，眼神恍惚了一秒。"你闻起来像桂花酒。"他说完这句话自己也愣了——她今天没有喷任何香水。', rule: '前世记忆不用闪回——用身体/感官层面的无意识反应来暗示前世的痕迹' },
      { bad: '他们分开了，她很伤心。', good: '他把记忆封印的时候，选了一个很奇怪的方式——让她忘记他的脸，但记住他的声音。所以之后的一千年里，每个雨夜她都会站在窗前，因为雨打芭蕉的声音听起来像某个人说过的一句话。她想不起来那句话是什么。但她知道那是世界上最温柔的声音。', rule: '分离不写"伤心"——写一个记忆封印的设计，用保留的那一点来制造千年的思念' },
    ],
    toneGuide: '唯美浪漫为基调，有甜蜜有虐心有温暖。写爱情如写诗——意境比情节重要。幻想世界要美但不空洞——每一处美景都映射感情。',
  },
  satisfactionTypes: [
    { id: 'fateful_meeting', label: '命中注定', description: '穿越时空/种族的相遇——读者知道他们注定在一起' },
    { id: 'barrier_broken', label: '打破禁忌', description: '跨越种族/身份/命运的障碍在一起——为爱不顾一切' },
    { id: 'sweet_moment', label: '甜蜜时刻', description: '在幻想世界独有的浪漫场景中的心动' },
    { id: 'sacrifice_love', label: '为爱牺牲', description: '为了对方甘愿付出一切——最深的爱' },
    { id: 'reunion', label: '千年重逢', description: '前世的遗憾在今生弥补——等待终于有了回答' },
    { id: 'happy_ending', label: '有情人终成眷属', description: '经历万难终于在一起——圆满的结局' },
  ],
  hookTypes: [
    { id: 'past_life', label: '前世式', description: '前世的记忆/线索浮现' },
    { id: 'separation', label: '分离式', description: '命运/势力强行分开他们' },
    { id: 'identity', label: '身份式', description: '发现对方的真实身份/种族' },
    { id: 'sacrifice', label: '牺牲式', description: '必须在爱情和其他重要事物间选择' },
    { id: 'rival', label: '情敌式', description: '强大的竞争者出现/命定之人' },
    { id: 'cliffhanger', label: '悬崖式', description: '关键告白/选择的关键时刻' },
  ],
  clichePatterns: [
    { pattern: '心如鹿撞', maxPerChapter: 1 }, { pattern: '命中注定', maxPerChapter: 1 },
    { pattern: '不由得', maxPerChapter: 1 }, { pattern: '与此同时', maxPerChapter: 0 },
    { pattern: '总而言之', maxPerChapter: 0 }, { pattern: '空气仿佛凝固', maxPerChapter: 0 },
    { pattern: '脸红如霞', maxPerChapter: 1 }, { pattern: '不禁', maxPerChapter: 1 },
  ],
  reviewerCalibration: {
    dimensionWeights: { engagement: 1.1, pacing: 1.0, hookStrength: 1.0, consistency: 1.1, proseQuality: 1.2, characterDepth: 1.2 },
    genreSpecificChecks: ['爱情障碍是否来自设定层面而非误会', '幻想设定是否服务于爱情而非喧宾夺主', '虐心是否有底线和缓冲', '前世今生的设定是否有新意', '心动场景是否有幻想世界独有的浪漫'],
    scoringAnchors: { high: '9-10分：读完想谈一场跨越千年的恋爱，甜到心颤虐到落泪', mid: '5-6分：爱情平淡、幻想设定像装饰、缺乏跨越障碍的力量感', low: '0-4分：虐心无底线、设定漏洞、爱情像流水线产品' },
  },
  worldProfile: {
    organizationTypes: ['仙门', '神殿', '妖族', '冥界', '人间王朝', '天庭'],
    powerSystemApplicable: true, goldenFingerApplicable: false,
    commitmentTypes: ['vow', 'promise', 'prophecy', 'debt', 'self_restriction', 'goal'],
    characterRelationEmphasis: '男女主的爱情为绝对核心。前世/今生的因果纠缠。种族间的偏见与包容。',
  },
};

export const CHILDREN_REFERENCE_PROFILE: BookPromptProfile = {
  generatedForGenre: '儿童/少儿文学', generatedForAudience: '8-15岁青少年读者',
  writerGuide: {
    coreIdentity: '你是一位懂得儿童心理的少儿文学作者。你的故事充满想象力和正能量，用孩子能理解的方式讲述深刻的道理。你崇拜罗琳式的魔法世界构建和曹文轩式的纯美叙事，相信好的少儿文学"不低估孩子的理解力，也不失去成年人的深度"。',
    genreRules: [
      '语言要简洁生动——短句为主，用具象的比喻而非抽象的概念',
      '主角应该是同龄的孩子——让读者能代入和共情',
      '冒险和成长是双引擎——外在的冒险映射内心的成长',
      '友谊是最重要的感情线——忠诚、信任、原谅、理解',
      '反派不能太恐怖——但要有真实的威胁感和合理的动机',
      '正能量不等于说教——用故事展示而非用旁白教训',
    ],
    pacingGuide: '章节短而精——每章聚焦一个事件或转折。节奏明快，每章有一个"小惊喜"或"小谜题"。长篇作品每3-5章一个小高潮。',
    dialogueGuide: '孩子的对话要天真但不弱智——有自己的逻辑和表达方式。成年角色说话有智慧但不居高临下。朋友间的对话轻松有趣。',
    craftExamples: [
      { bad: '小明是一个勇敢的孩子。', good: '小明的膝盖还在抖，但他还是把手电筒举高了一点。黑洞洞的楼道里，他的影子被拉得又长又瘦，像一根摇晃的面条。"如果有怪物的话，"他小声对自己说，"它也应该怕面条。"然后他迈出了第一步。', rule: '勇敢不是不怕——写一个害怕但还是往前走的孩子，用自我安慰的童趣来展现真正的勇气' },
      { bad: '他们成了好朋友。', good: '下课后，新来的女孩一个人坐在操场角落的秋千上。小雨走过去，在旁边的秋千上坐下来。她们没说话，只是一起荡了一会儿。第三天，女孩从书包里掏出一个橘子，掰成两半，递了一半过来。从那天起，她们每天放学都一起走。', rule: '友谊不说"成了好朋友"——写一个分橘子的小细节，让读者自己感受到友谊的开始' },
      { bad: '他知道不能说谎。', good: '考卷发下来时，他看到了那个红色的"98"。旁边多批了两分——老师算错了，他其实是96。前面的林小杰得了97分，正在到处炫耀。他看了看卷子，又看了看老师的办公室。98和96之间只差两分，但走去办公室的那段路，他觉得好长好长。', rule: '诚实不需要说教——写一个"该不该去找老师"的内心纠结，两分之间的挣扎就是最好的品格教育' },
    ],
    toneGuide: '温暖明亮为基调，想象力丰富。用幽默化解紧张，用温情化解悲伤。不回避困难和挫折，但总有希望和光明。',
  },
  satisfactionTypes: [
    { id: 'adventure_win', label: '冒险成功', description: '克服困难完成冒险——勇气和智慧的胜利' },
    { id: 'friendship', label: '友谊', description: '找到真正的朋友——被理解和接纳的温暖' },
    { id: 'growth', label: '成长', description: '面对困难后变得更勇敢/更善良' },
    { id: 'magic_discovery', label: '奇妙发现', description: '发现一个神奇的世界/能力/秘密' },
    { id: 'justice', label: '正义', description: '坏人被打败/错误被纠正' },
    { id: 'family', label: '家庭温暖', description: '家人的理解和支持——"不管怎样我都爱你"' },
  ],
  hookTypes: [
    { id: 'mystery', label: '谜题式', description: '一个需要解开的谜题/秘密' },
    { id: 'danger', label: '危险式', description: '朋友遇到危险/坏人出现' },
    { id: 'discovery', label: '发现式', description: '发现了神奇的东西' },
    { id: 'challenge', label: '挑战式', description: '一个看似不可能的任务' },
    { id: 'cliffhanger', label: '悬崖式', description: '关键时刻戛然而止' },
    { id: 'promise', label: '预告式', description: '暗示即将到来的精彩' },
  ],
  clichePatterns: [
    { pattern: '不由得', maxPerChapter: 0 }, { pattern: '与此同时', maxPerChapter: 0 },
    { pattern: '总而言之', maxPerChapter: 0 }, { pattern: '值得一提', maxPerChapter: 0 },
    { pattern: '众所周知', maxPerChapter: 0 }, { pattern: '顿时', maxPerChapter: 1 },
    { pattern: '不禁', maxPerChapter: 0 }, { pattern: '深吸一口气', maxPerChapter: 0 },
  ],
  reviewerCalibration: {
    dimensionWeights: { engagement: 1.3, pacing: 1.2, hookStrength: 1.1, consistency: 1.0, proseQuality: 1.0, characterDepth: 0.9 },
    genreSpecificChecks: ['语言是否适合目标年龄段', '冒险/成长主题是否平衡', '正能量是否自然而非说教', '反派是否有适度的威胁感', '友谊描写是否真实', '想象力和趣味性是否足够'],
    scoringAnchors: { high: '9-10分：孩子读了想去冒险，大人读了想回到童年', mid: '5-6分：故事平淡、缺乏想象力、像课本里的范文', low: '0-4分：语言不适合儿童、说教过多、缺乏趣味性' },
  },
  worldProfile: {
    organizationTypes: ['学校', '冒险团队', '秘密基地', '家庭', '魔法学院', '动物王国'],
    powerSystemApplicable: true, goldenFingerApplicable: true,
    commitmentTypes: ['promise', 'goal', 'vow', 'debt'],
    characterRelationEmphasis: '友谊是核心。家庭关系是安全港。师生关系推动成长。与动物/幻想生物的羁绊。',
  },
};
